language: ruby
notifications:
  email:
    - levi@leviwilson.com
before_install:
  - gem install calabash-android
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - export ANDROID_HOME=~/builds/leandog/gametel/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,2 --no-ui --force
  - android update sdk --filter 5,10,29,33 --no-ui --force
  - android list targets
  - android list sdk
